import type { Metadata } from "next";



export const metadata: Metadata = {
  title: "Next App Home Page",
  description: "Generated by create next app Home Page",
  
  openGraph:{
    title: "Next App Home Page",
    description: "Generated by create next app Home Page",
    url: "https://nextjs13-course.vercel.app",
    type: "website",
    // site_name: "Next App",
    locale: "en_US",
    // image:[{
    //   url: "https://nextjs13-course.vercel.app/images/nextjs-logo.png",
    //   width: 600,
    //   height: 315,
    //   alt: "Next.js Logo"
    // }]
  }


};


// import Header from '@/app/components/Header'
export default function Home() {
  return (
    
    <div>
      {/* <Header name={"mahmoud gamal"}/>
      hello world Eng: Mahmoud Gamal !
      <Header name={"Ahmed Bakheet"}/> */}
      
      <h1>Main Page</h1>


    </div>
  );
}






// fetching caching notifications context store actions 










